usermanagement_homepage:
    pattern:  /user/{name}
    defaults: { _controller: UsermanagementBundle:Default:index }

blog_show:
    path:      /user_testing/
    defaults:  { _controller: UsermanagementBundle:Default:show }
